version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "10000:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata:/data
volumes:
  postgresdata: